version: '3.0'
services:
  server:
    container_name: server
    stdin_open: true
    restart: always
    build: ./server/
    ports:
      - "8000:8000"

  client:
    container_name: client
    stdin_open: true
    restart: always
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
